name: Auto Assign to Project(s)
env:
  ADD_TO_PROJECT_PAT: ${{ secrets.ADD_TO_PROJECT_PAT }}
on:
  issues:
    types:
      - opened
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/add-to-project@v2 # v2.0.2
        with:
          project-url: https://github.com/orgs/ESA-eodashboards/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
